# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeType', models.CharField(choices=[('S', b'Staff'), ('F', b'Freelance')], max_length=1, validators=[djchoices.choices.ChoicesValidator({'F': b'Freelance', 'S': b'Staff'})])),
                ('rate', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumberyard.Departments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_num', models.CharField(max_length=200)),
                ('job_name', models.CharField(max_length=200)),
                ('date_awarded', models.DateTimeField(verbose_name='date awarded')),
                ('email_alias', models.CharField(max_length=200)),
                ('agency', models.CharField(max_length=200)),
                ('agency_prod', models.CharField(max_length=200)),
                ('agency_prod_email', models.CharField(max_length=200)),
                ('agency_prod_phone', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('client_contact_name', models.CharField(max_length=200)),
                ('client_contact_email', models.CharField(max_length=200)),
                ('client_contact_phone', models.CharField(max_length=200)),
                ('milestones', models.CharField(max_length=200)),
                ('date_pitch', models.DateTimeField(verbose_name='date pitched')),
                ('date_delivery', models.DateTimeField(verbose_name='date delivery')),
                ('delivery_specs', models.CharField(max_length=200)),
                ('artist_list', models.ManyToManyField(to='lumberyard.Employee')),
                ('lead_2D', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_lead_2D', to='lumberyard.Employee')),
                ('lead_3D', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_lead_3D', to='lumberyard.Employee')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_producer', to='lumberyard.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_num', models.IntegerField(default=0)),
                ('sequence_length', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(verbose_name='date due')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumberyard.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
