# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='sequence_name',
            field=models.CharField(default=datetime.datetime(2016, 7, 21, 21, 8, 34, 336205, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
