# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0002_sequence_sequence_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AddField(
            model_name='sequence',
            name='notes',
            field=models.TextField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='url',
            field=models.CharField(default='NONE', max_length=200),
        ),
    ]
