# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0003_auto_20160721_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(default='1080p Prorez QT', max_length=200)),
                ('spec_rez', models.CharField(default='1920x1080', max_length=50)),
                ('spec_format', models.CharField(default='Quicktime', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='agency',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='agency_prod',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='agency_prod_email',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='agency_prod_phone',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_contact_email',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_contact_name',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_contact_phone',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='date_delivery',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date delivery'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='date_pitch',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date pitched'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='delivery_specs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumberyard.DeliverySpecs'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='email_alias',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='milestones',
            field=models.CharField(default='NONE', max_length=200),
        ),
    ]
