# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0005_auto_20160722_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='date_delivery',
        ),
    ]
