# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import lumberyard.models


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0006_remove_jobs_date_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date_delivery',
            field=models.DateTimeField(default=lumberyard.models.date_plus_30, verbose_name='date delivery'),
        ),
    ]
