# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0007_jobs_date_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_awarded',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
