# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0009_auto_20160722_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_active',
            field=models.BooleanField(default=True),
        ),
    ]
