# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0013_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='email_alias',
            field=models.EmailField(default='NONE', max_length=254),
        ),
    ]
