# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0014_auto_20160723_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('render_name', models.CharField(max_length=100)),
                ('render_timeStamp', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('render_artist', models.CharField(max_length=100)),
                ('render_path', models.CharField(max_length=100)),
                ('render_notes', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='name',
        ),
        migrations.AddField(
            model_name='sequence',
            name='tasks',
            field=models.ManyToManyField(to='lumberyard.Tasks'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='taskType',
            field=models.CharField(choices=[('anim', b'animation'), ('color', b'colorAndLighting'), ('track', b'tracking'), ('dyn', b'dynamics'), ('text', b'texture'), ('comp', b'comp'), ('model', b'modeling'), ('design', b'design')], default='anim', max_length=20, validators=[djchoices.choices.ChoicesValidator({'anim': b'animation', 'color': b'colorAndLighting', 'comp': b'comp', 'design': b'design', 'dyn': b'dynamics', 'model': b'modeling', 'text': b'texture', 'track': b'tracking'})]),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='due_date',
            field=models.DateTimeField(verbose_name='due date'),
        ),
        migrations.AddField(
            model_name='renders',
            name='shot_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumberyard.Sequence'),
        ),
    ]
