# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0015_auto_20160817_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renders',
            options={'verbose_name': 'Renders', 'verbose_name_plural': 'Renders'},
        ),
        migrations.AlterField(
            model_name='renders',
            name='render_timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskType',
            field=models.CharField(choices=[('ANIMATION', b'animation'), ('COLOR & LIGHTING', b'colorAndLighting'), ('TRACKIGN', b'tracking'), ('DYNAMICS', b'dynamics'), ('TEXTURE', b'texture'), ('COMP', b'comp'), ('MODELING', b'modeling'), ('DESIGN', b'design')], default='anim', max_length=20, validators=[djchoices.choices.ChoicesValidator({'ANIMATION': b'animation', 'COLOR & LIGHTING': b'colorAndLighting', 'COMP': b'comp', 'DESIGN': b'design', 'DYNAMICS': b'dynamics', 'MODELING': b'modeling', 'TEXTURE': b'texture', 'TRACKIGN': b'tracking'})]),
        ),
    ]
