# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0016_auto_20160817_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='email_alias',
            field=models.EmailField(default='none@woodshop.tv', max_length=254),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskType',
            field=models.CharField(choices=[('ANIMATION', b'animation'), ('COLOR & LIGHTING', b'colorAndLighting'), ('TRACKIGN', b'tracking'), ('DYNAMICS', b'dynamics'), ('TEXTURE', b'texture'), ('COMP', b'comp'), ('MODELING', b'modeling'), ('DESIGN', b'design')], default='ANIMATION', max_length=20, validators=[djchoices.choices.ChoicesValidator({'ANIMATION': b'animation', 'COLOR & LIGHTING': b'colorAndLighting', 'COMP': b'comp', 'DESIGN': b'design', 'DYNAMICS': b'dynamics', 'MODELING': b'modeling', 'TEXTURE': b'texture', 'TRACKIGN': b'tracking'})]),
        ),
    ]
