# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumberyard', '0017_auto_20160817_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='sequence_num',
            field=models.CharField(max_length=10),
        ),
    ]
